---
server:
  gateway: crls.pki.goog  # ip or fqdn to check used for connectivity checks
  interval: 15            # update interval to check for new crls, minutes

ca:
  id: 
    - x21
    - x11
  uri: 
    - http://crls.pki.goog/gts1c3/zdATt0Ex_Fk.crl
    - http://crl.godaddy.com/gdig2s1-5609.crl
