---
default:
  gateway: crls.pki.goog    # ip or fqdn to check used for connectivity checks
  interval: 5             # update interval to check for new crls, in seconds
  webserver: false          # enables built-in webserver, when true
  port: 4000                # port used by built-in webserver

ca:
  id: 
    - x21
    - x11
  uri: 
    - http://crls.pki.goog/gts1c3/zdATt0Ex_Fk.cr
    - http://crl.godaddy.com/gdig2s1-5609.crl
