name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  ghcr-build:
    name: GHCR Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: gorevoke
          registry: ghcr.io
          dockerfile: build/docker/Dockerfile
          addLatest: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    name: Docker Hub Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: s0lution/gorevoke
          registry: docker.io
          dockerfile: build/docker/Dockerfile
          addLatest: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}