name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ghcr.io/acavella/gorevoke
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
